export const DICES_ROLLED = 'DICES_ROLLED';
export const DICE_LOCKED = 'DICE_LOCKED';
export const CURRENT_VALUES_GENERATED = 'CURRENT_VALUES_GENERATED';
export const FIVES_SELECTED = 'FIVES_SELECTED';
export const ONE_PAIR_SELECTED = 'ONE_PAIR_SELECTED';
export const CHANCE_SELECTED = 'CHANCE_SELECTED';

